[2019-03-26 18:28:13,792]-[INFO]-Python14--------登录用例开始执行了-------
[2019-03-26 18:28:13,871]-[INFO]-Python14-正在执行第001条用例，参数为{'mobilephone':'${mobile}','pwd':'${pwd}'}
[2019-03-26 18:28:13,949]-[ERROR]-Python14-实际结果与期望结果一致，错误为{'code': '20111', 'msg': '用户名或密码错误', 'status': 0} != {'code': '10001', 'msg': '登录成功', 'status': 1}
- {'code': '20111', 'msg': '用户名或密码错误', 'status': 0}
?           ^ ^^            ^^^^^^^^             ^

+ {'code': '10001', 'msg': '登录成功', 'status': 1}
?           ^ ^^            ^^^^             ^

[2019-03-26 18:28:14,219]-[INFO]-Python14---------登录用例执行结束了--------
[2019-03-26 18:28:14,268]-[INFO]-Python14--------登录用例开始执行了-------
[2019-03-26 18:28:14,276]-[INFO]-Python14-正在执行第002条用例，参数为{'mobilephone':'18168392262','pwd':'1234'}
[2019-03-26 18:28:14,611]-[INFO]-Python14---------登录用例执行结束了--------
[2019-03-26 18:28:14,618]-[INFO]-Python14--------登录用例开始执行了-------
[2019-03-26 18:28:14,624]-[INFO]-Python14-正在执行第003条用例，参数为{'mobilephone':'15168392262','pwd':'1234'}
[2019-03-26 18:28:14,961]-[INFO]-Python14---------登录用例执行结束了--------
[2019-03-26 18:28:14,969]-[INFO]-Python14--------登录用例开始执行了-------
[2019-03-26 18:28:14,975]-[INFO]-Python14-正在执行第004条用例，参数为{'mobilephone':'15168392262'}
[2019-03-26 18:28:15,315]-[INFO]-Python14---------登录用例执行结束了--------
[2019-03-26 18:28:15,322]-[INFO]-Python14--------登录用例开始执行了-------
[2019-03-26 18:28:15,328]-[INFO]-Python14-正在执行第005条用例，参数为{'pwd':'1234'}
[2019-03-26 18:28:15,673]-[INFO]-Python14---------登录用例执行结束了--------
